<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net48;net10.0-windows10.0.26100.0</TargetFrameworks>
		<OutputType>Exe</OutputType>
		<Platforms>AnyCPU;x64;x86</Platforms>
		<UseWPF>true</UseWPF>
		<UseWindowsForms>true</UseWindowsForms>
		<IsPackable>false</IsPackable>
	</PropertyGroup>

	<PropertyGroup>
		<MetroBinaryTfm Condition="'$(TargetFramework)' == 'net48'">net48</MetroBinaryTfm>
		<MetroBinaryTfm Condition="'$(TargetFramework)' == 'net10.0-windows10.0.26100.0'">net10.0-windows</MetroBinaryTfm>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="xunit.v3" Version="3.2.2" />
		<PackageReference Include="xunit.runner.visualstudio" Version="3.1.5" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\SylphyHorn.Core\SylphyHorn.Core.csproj" />
		<ProjectReference Include="..\SylphyHorn\SylphyHorn.csproj">
			<AdditionalProperties>RunSylphyHornPostBuild=false</AdditionalProperties>
		</ProjectReference>
		<Reference Include="MetroTrilithon">
			<HintPath>..\libraries\MetroTrilithon.Desktop\$(MetroBinaryTfm)\MetroTrilithon.dll</HintPath>
		</Reference>
	</ItemGroup>

</Project>
