//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SylphyHorn.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SylphyHorn.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   default に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Default {
            get {
                return ResourceManager.GetString("Common_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   provided by Windows に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_ProvidedByWinows {
            get {
                return ResourceManager.GetString("Common_ProvidedByWinows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reference に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Reference {
            get {
                return ResourceManager.GetString("Common_Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Also close these desktop names.
        /// </summary>
        public static string Placement_CloseByName {
            get {
                return ResourceManager.GetString("Placement_CloseByName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Also close these desktop numbers.
        /// </summary>
        public static string Placement_CloseByNumber {
            get {
                return ResourceManager.GetString("Placement_CloseByNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Close automatically created desktops without listing them below.
        /// </summary>
        public static string Placement_CloseCreated {
            get {
                return ResourceManager.GetString("Placement_CloseCreated", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to After use, close from the last desktop when empty for one second. Closing the current desktop switches to the previous desktop. App placement must be enabled..
        /// </summary>
        public static string Placement_CloseHint {
            get {
                return ResourceManager.GetString("Placement_CloseHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Automatically close empty desktops.
        /// </summary>
        public static string Placement_CloseTitle {
            get {
                return ResourceManager.GetString("Placement_CloseTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Create missing desktops when a matching app opens.
        /// </summary>
        public static string Placement_CreateMissing {
            get {
                return ResourceManager.GetString("Placement_CreateMissing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Default ({0}).
        /// </summary>
        public static string Placement_FollowDefaultState {
            get {
                return ResourceManager.GetString("Placement_FollowDefaultState", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Default desktop switching after placement.
        /// </summary>
        public static string Placement_FollowForeground {
            get {
                return ResourceManager.GetString("Placement_FollowForeground", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string Placement_FollowNo {
            get {
                return ResourceManager.GetString("Placement_FollowNo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string Placement_FollowYes {
            get {
                return ResourceManager.GetString("Placement_FollowYes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Switch.
        /// </summary>
        public static string Placement_FollowColumn {
            get {
                return ResourceManager.GetString("Placement_FollowColumn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Switching applies only to the window that was in the foreground immediately before placement..
        /// </summary>
        public static string Placement_FollowHint {
            get {
                return ResourceManager.GetString("Placement_FollowHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Rearrange existing windows.
        /// </summary>
        public static string Placement_ApplyHeading {
            get {
                return ResourceManager.GetString("Placement_ApplyHeading", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Apply these rules to windows that are already open. Choose the windows from a list before moving them..
        /// </summary>
        public static string Placement_ApplyHint {
            get {
                return ResourceManager.GetString("Placement_ApplyHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Placement_DeleteLabel {
            get {
                return ResourceManager.GetString("Placement_DeleteLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to If multiple desktops have the same name, windows are placed on the lowest-numbered desktop..
        /// </summary>
        public static string Placement_NameMatchHint {
            get {
                return ResourceManager.GetString("Placement_NameMatchHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Background に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Background {
            get {
                return ResourceManager.GetString("Settings_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change the background for each desktop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Background_ChangeBackground {
            get {
                return ResourceManager.GetString("Settings_Background_ChangeBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Desktop background に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Background_Desktop {
            get {
                return ResourceManager.GetString("Settings_Background_Desktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wallpaper: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Background_Image {
            get {
                return ResourceManager.GetString("Settings_Background_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Supported image formats: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Background_Note1 {
            get {
                return ResourceManager.GetString("Settings_Background_Note1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Note: Please prepare image files with the virtual desktop number as filename (e.g. &quot;1.png&quot;, &quot;2.png&quot;, ...). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Background_Note2 {
            get {
                return ResourceManager.GetString("Settings_Background_Note2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fit: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Background_Position {
            get {
                return ResourceManager.GetString("Settings_Background_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Center に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Background_Position_Center {
            get {
                return ResourceManager.GetString("Settings_Background_Position_Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fill に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Background_Position_Fill {
            get {
                return ResourceManager.GetString("Settings_Background_Position_Fill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Background_Position_Fit {
            get {
                return ResourceManager.GetString("Settings_Background_Position_Fit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Span に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Background_Position_Span {
            get {
                return ResourceManager.GetString("Settings_Background_Position_Span", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stretch に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Background_Position_Stretch {
            get {
                return ResourceManager.GetString("Settings_Background_Position_Stretch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tile に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Background_Position_Tile {
            get {
                return ResourceManager.GetString("Settings_Background_Position_Tile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Background Image に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Background_SelectionDialog {
            get {
                return ResourceManager.GetString("Settings_Background_SelectionDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Source image file path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Background_SourceImageFile {
            get {
                return ResourceManager.GetString("Settings_Background_SourceImageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Source image folder path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Background_SourceImageFolder {
            get {
                return ResourceManager.GetString("Settings_Background_SourceImageFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close desktop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_CloseDesktop {
            get {
                return ResourceManager.GetString("Settings_CloseDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close and switch to left: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_CloseDesktop_CloseAndSwitchLeft {
            get {
                return ResourceManager.GetString("Settings_CloseDesktop_CloseAndSwitchLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close and switch to right: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_CloseDesktop_CloseAndSwitchRight {
            get {
                return ResourceManager.GetString("Settings_CloseDesktop_CloseAndSwitchRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Desktop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Desktop {
            get {
                return ResourceManager.GetString("Settings_Desktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Click to switch to this desktop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Desktop_ClickToSwitchDesktop {
            get {
                return ResourceManager.GetString("Settings_Desktop_ClickToSwitchDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Desktop_CloseDesktop {
            get {
                return ResourceManager.GetString("Settings_Desktop_CloseDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close this desktop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Desktop_CloseDesktop_CloseThisDesktop {
            get {
                return ResourceManager.GetString("Settings_Desktop_CloseDesktop_CloseThisDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New desktop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Desktop_CreateDesktop {
            get {
                return ResourceManager.GetString("Settings_Desktop_CreateDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   First に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Desktop_MoveDesktopFirst {
            get {
                return ResourceManager.GetString("Settings_Desktop_MoveDesktopFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Last に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Desktop_MoveDesktopLast {
            get {
                return ResourceManager.GetString("Settings_Desktop_MoveDesktopLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Next に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Desktop_MoveDesktopNext {
            get {
                return ResourceManager.GetString("Settings_Desktop_MoveDesktopNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Previous に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Desktop_MoveDesktopPrevious {
            get {
                return ResourceManager.GetString("Settings_Desktop_MoveDesktopPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Override virtual desktops with settings of SylphyHorn on startup に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Desktop_OverrideSettingsOnStartup {
            get {
                return ResourceManager.GetString("Settings_Desktop_OverrideSettingsOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reorder: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Desktop_Reorder {
            get {
                return ResourceManager.GetString("Settings_Desktop_Reorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Desktop settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Desktop_Settings {
            get {
                return ResourceManager.GetString("Settings_Desktop_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Desktop names に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_DesktopNames {
            get {
                return ResourceManager.GetString("Settings_DesktopNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Display a desktop name in notification window に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_DesktopNames_UseDesktopName {
            get {
                return ResourceManager.GetString("Settings_DesktopNames_UseDesktopName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Desktop switching に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_DesktopSwitching {
            get {
                return ResourceManager.GetString("Settings_DesktopSwitching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loop virtual desktops に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_DesktopSwitching_Loop {
            get {
                return ResourceManager.GetString("Settings_DesktopSwitching_Loop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Override OS default key combination (Ctrl+Win+Left and Right) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_DesktopSwitching_OverrideOS {
            get {
                return ResourceManager.GetString("Settings_DesktopSwitching_OverrideOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   General に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_General {
            get {
                return ResourceManager.GetString("Settings_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You must restart app in order for the changes to take all effect. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Language_RequireRestartMessage {
            get {
                return ResourceManager.GetString("Settings_Language_RequireRestartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   App log に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Log {
            get {
                return ResourceManager.GetString("Settings_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Event viewer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_LogViewer {
            get {
                return ResourceManager.GetString("Settings_LogViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Events that occurred during execution are displayed here. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_LogViewer_Description {
            get {
                return ResourceManager.GetString("Settings_LogViewer_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Managing settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ManagingSettings {
            get {
                return ResourceManager.GetString("Settings_ManagingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ManagingSettings_Export {
            get {
                return ResourceManager.GetString("Settings_ManagingSettings_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export settings to an XML file to make a backup. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ManagingSettings_ExportDetail {
            get {
                return ResourceManager.GetString("Settings_ManagingSettings_ExportDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save Settings As... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ManagingSettings_ExportDialog {
            get {
                return ResourceManager.GetString("Settings_ManagingSettings_ExportDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Import... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ManagingSettings_Import {
            get {
                return ResourceManager.GetString("Settings_ManagingSettings_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Import settings from an XML file you stored. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ManagingSettings_ImportDetail {
            get {
                return ResourceManager.GetString("Settings_ManagingSettings_ImportDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Settings to Import に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ManagingSettings_ImportDialog {
            get {
                return ResourceManager.GetString("Settings_ManagingSettings_ImportDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirm Override Desktops に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ManagingSettings_OverrideDesktopsConfirmationDialog {
            get {
                return ResourceManager.GetString("Settings_ManagingSettings_OverrideDesktopsConfirmationDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you override virtual desktops with settings of SylphyHorn? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ManagingSettings_OverrideDesktopsConfirmationMessage {
            get {
                return ResourceManager.GetString("Settings_ManagingSettings_OverrideDesktopsConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset to default に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ManagingSettings_Reset {
            get {
                return ResourceManager.GetString("Settings_ManagingSettings_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirm Reset に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ManagingSettings_ResetConfirmationDialog {
            get {
                return ResourceManager.GetString("Settings_ManagingSettings_ResetConfirmationDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This will delete all settings. Are you sure to reset? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ManagingSettings_ResetConfirmationMessage {
            get {
                return ResourceManager.GetString("Settings_ManagingSettings_ResetConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset settings to default. This will delete all settings. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ManagingSettings_ResetDetail {
            get {
                return ResourceManager.GetString("Settings_ManagingSettings_ResetDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mouse に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_MouseShortcut {
            get {
                return ResourceManager.GetString("Settings_MouseShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move active window to adjacent desktop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_MoveWindowToAdjacentDesktop {
            get {
                return ResourceManager.GetString("Settings_MoveWindowToAdjacentDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Left: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_MoveWindowToAdjacentDesktop_Left {
            get {
                return ResourceManager.GetString("Settings_MoveWindowToAdjacentDesktop_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Left (Switch): に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_MoveWindowToAdjacentDesktop_LeftAndSwitch {
            get {
                return ResourceManager.GetString("Settings_MoveWindowToAdjacentDesktop_LeftAndSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Right: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_MoveWindowToAdjacentDesktop_Right {
            get {
                return ResourceManager.GetString("Settings_MoveWindowToAdjacentDesktop_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Right (Switch): に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_MoveWindowToAdjacentDesktop_RightAndSwitch {
            get {
                return ResourceManager.GetString("Settings_MoveWindowToAdjacentDesktop_RightAndSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move active window to created new desktop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_MoveWindowToCreatedDesktop {
            get {
                return ResourceManager.GetString("Settings_MoveWindowToCreatedDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Switch only: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_MoveWindowToCreatedDesktop_CreateOnly {
            get {
                return ResourceManager.GetString("Settings_MoveWindowToCreatedDesktop_CreateOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_MoveWindowToCreatedDesktop_Move {
            get {
                return ResourceManager.GetString("Settings_MoveWindowToCreatedDesktop_Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move (Switch): に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_MoveWindowToCreatedDesktop_MoveAndSwitch {
            get {
                return ResourceManager.GetString("Settings_MoveWindowToCreatedDesktop_MoveAndSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move active window to specified desktop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_MoveWindowToSpecifiedDesktop {
            get {
                return ResourceManager.GetString("Settings_MoveWindowToSpecifiedDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Previous: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_MoveWindowToSpecifiedDesktop_Previous {
            get {
                return ResourceManager.GetString("Settings_MoveWindowToSpecifiedDesktop_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move active window to specified desktop and switch to it に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_MoveWindowToSpecifiedDesktopAndSwitch {
            get {
                return ResourceManager.GetString("Settings_MoveWindowToSpecifiedDesktopAndSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Previous: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_MoveWindowToSpecifiedDesktopAndSwitch_Previous {
            get {
                return ResourceManager.GetString("Settings_MoveWindowToSpecifiedDesktopAndSwitch_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Destination displays に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_MultipleDisplays {
            get {
                return ResourceManager.GetString("Settings_MultipleDisplays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All displays に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_MultipleDisplays_AllDisplays {
            get {
                return ResourceManager.GetString("Settings_MultipleDisplays_AllDisplays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current display に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_MultipleDisplays_CurrentDisplay {
            get {
                return ResourceManager.GetString("Settings_MultipleDisplays_CurrentDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Display {0}: {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_MultipleDisplays_EachDisplay {
            get {
                return ResourceManager.GetString("Settings_MultipleDisplays_EachDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Notification に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Notification {
            get {
                return ResourceManager.GetString("Settings_Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Always show current desktop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Notification_AlwaysShowDesktop {
            get {
                return ResourceManager.GetString("Settings_Notification_AlwaysShowDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Display a notification when switched virtual desktop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Notification_Display {
            get {
                return ResourceManager.GetString("Settings_Notification_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Time Duration for Notification Messages: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Notification_Display_Duration {
            get {
                return ResourceManager.GetString("Settings_Notification_Display_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ms に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Notification_Display_Duration_Milliseconds {
            get {
                return ResourceManager.GetString("Settings_Notification_Display_Duration_Milliseconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Other options に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Notification_Others {
            get {
                return ResourceManager.GetString("Settings_Notification_Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Simple notification mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Notification_SimpleMode {
            get {
                return ResourceManager.GetString("Settings_Notification_SimpleMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Notification corner style に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationCornerStyle {
            get {
                return ResourceManager.GetString("Settings_NotificationCornerStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not rounded (Windows 10 style) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationCornerStyle_NotRounded {
            get {
                return ResourceManager.GetString("Settings_NotificationCornerStyle_NotRounded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rounded (Windows 11 style) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationCornerStyle_Rounded {
            get {
                return ResourceManager.GetString("Settings_NotificationCornerStyle_Rounded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Small rounded に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationCornerStyle_SmallRounded {
            get {
                return ResourceManager.GetString("Settings_NotificationCornerStyle_SmallRounded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Notification font family に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationFontFamily {
            get {
                return ResourceManager.GetString("Settings_NotificationFontFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Notification font size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationFontSize {
            get {
                return ResourceManager.GetString("Settings_NotificationFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Body: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationFontSize_Body {
            get {
                return ResourceManager.GetString("Settings_NotificationFontSize_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Header: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationFontSize_Header {
            get {
                return ResourceManager.GetString("Settings_NotificationFontSize_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Line Spacing: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationFontSize_LineSpacing {
            get {
                return ResourceManager.GetString("Settings_NotificationFontSize_LineSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Notification text alignment に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationTextAlignment {
            get {
                return ResourceManager.GetString("Settings_NotificationTextAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Body: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationTextAlignment_Body {
            get {
                return ResourceManager.GetString("Settings_NotificationTextAlignment_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Center に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationTextAlignment_Center {
            get {
                return ResourceManager.GetString("Settings_NotificationTextAlignment_Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Header: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationTextAlignment_Header {
            get {
                return ResourceManager.GetString("Settings_NotificationTextAlignment_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Left に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationTextAlignment_Left {
            get {
                return ResourceManager.GetString("Settings_NotificationTextAlignment_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Right に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationTextAlignment_Right {
            get {
                return ResourceManager.GetString("Settings_NotificationTextAlignment_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Notification window minimum size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationWindowMinSize {
            get {
                return ResourceManager.GetString("Settings_NotificationWindowMinSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Height: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationWindowMinSize_Height {
            get {
                return ResourceManager.GetString("Settings_NotificationWindowMinSize_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Width: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationWindowMinSize_Width {
            get {
                return ResourceManager.GetString("Settings_NotificationWindowMinSize_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pin: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationWindowMinSize_Width_PinWindow {
            get {
                return ResourceManager.GetString("Settings_NotificationWindowMinSize_Width_PinWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Simple: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationWindowMinSize_Width_SimpleMode {
            get {
                return ResourceManager.GetString("Settings_NotificationWindowMinSize_Width_SimpleMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Notification offset に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationWindowOffset {
            get {
                return ResourceManager.GetString("Settings_NotificationWindowOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pin: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationWindowOffset_PinWindow {
            get {
                return ResourceManager.GetString("Settings_NotificationWindowOffset_PinWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Desktop: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationWindowOffset_SwitchDesktop {
            get {
                return ResourceManager.GetString("Settings_NotificationWindowOffset_SwitchDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Notification placement に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationWindowPlacement {
            get {
                return ResourceManager.GetString("Settings_NotificationWindowPlacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bottom center に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationWindowPlacement_BottomCenter {
            get {
                return ResourceManager.GetString("Settings_NotificationWindowPlacement_BottomCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bottom left に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationWindowPlacement_BottomLeft {
            get {
                return ResourceManager.GetString("Settings_NotificationWindowPlacement_BottomLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bottom right に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationWindowPlacement_BottomRight {
            get {
                return ResourceManager.GetString("Settings_NotificationWindowPlacement_BottomRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Center に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationWindowPlacement_Center {
            get {
                return ResourceManager.GetString("Settings_NotificationWindowPlacement_Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Center left に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationWindowPlacement_CenterLeft {
            get {
                return ResourceManager.GetString("Settings_NotificationWindowPlacement_CenterLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Center right に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationWindowPlacement_CenterRight {
            get {
                return ResourceManager.GetString("Settings_NotificationWindowPlacement_CenterRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Top center に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationWindowPlacement_TopCenter {
            get {
                return ResourceManager.GetString("Settings_NotificationWindowPlacement_TopCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Top left に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationWindowPlacement_TopLeft {
            get {
                return ResourceManager.GetString("Settings_NotificationWindowPlacement_TopLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Top right に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationWindowPlacement_TopRight {
            get {
                return ResourceManager.GetString("Settings_NotificationWindowPlacement_TopRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Notification window style に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationWindowStyle {
            get {
                return ResourceManager.GetString("Settings_NotificationWindowStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Accent に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationWindowStyle_Accent {
            get {
                return ResourceManager.GetString("Settings_NotificationWindowStyle_Accent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Match to Apps に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationWindowStyle_Apps {
            get {
                return ResourceManager.GetString("Settings_NotificationWindowStyle_Apps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dark に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationWindowStyle_Dark {
            get {
                return ResourceManager.GetString("Settings_NotificationWindowStyle_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Light に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationWindowStyle_Light {
            get {
                return ResourceManager.GetString("Settings_NotificationWindowStyle_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Match to System に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationWindowStyle_System {
            get {
                return ResourceManager.GetString("Settings_NotificationWindowStyle_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Operate SylphyHornPlus に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_OperateSylphyHorn {
            get {
                return ResourceManager.GetString("Settings_OperateSylphyHorn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pin window: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Pin {
            get {
                return ResourceManager.GetString("Settings_Pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pin/Unpin toggle: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_PinToggle {
            get {
                return ResourceManager.GetString("Settings_PinToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pin window to all desktops に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_PinWindow {
            get {
                return ResourceManager.GetString("Settings_PinWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pin window from app to all desktops に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_PinWindowFromApp {
            get {
                return ResourceManager.GetString("Settings_PinWindowFromApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Placement に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Placement {
            get {
                return ResourceManager.GetString("Settings_Placement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shortcut key に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ShortcutKey {
            get {
                return ResourceManager.GetString("Settings_ShortcutKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show only current desktop number (simple mode) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ShowOnlyCurrentNumberInTray {
            get {
                return ResourceManager.GetString("Settings_ShowOnlyCurrentNumberInTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show settings: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ShowSettings {
            get {
                return ResourceManager.GetString("Settings_ShowSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Startup に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Startup {
            get {
                return ResourceManager.GetString("Settings_Startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Automaticaly start at logon に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Startup_Automaticaly {
            get {
                return ResourceManager.GetString("Settings_Startup_Automaticaly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Automaticaly start as administrator at logon (from Task Scheduler) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Startup_Automaticaly_As_Admin {
            get {
                return ResourceManager.GetString("Settings_Startup_Automaticaly_As_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Swap desktop (Windows 11) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_SwapDesktop {
            get {
                return ResourceManager.GetString("Settings_SwapDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   First: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_SwapDesktop_First {
            get {
                return ResourceManager.GetString("Settings_SwapDesktop_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Last: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_SwapDesktop_Last {
            get {
                return ResourceManager.GetString("Settings_SwapDesktop_Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Left: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_SwapDesktop_Left {
            get {
                return ResourceManager.GetString("Settings_SwapDesktop_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Right: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_SwapDesktop_Right {
            get {
                return ResourceManager.GetString("Settings_SwapDesktop_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Swap for specified desktop (Windows 11) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_SwapSpecifiedDesktop {
            get {
                return ResourceManager.GetString("Settings_SwapSpecifiedDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Switch to adjacent desktop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_SwitchAdjacentDesktop {
            get {
                return ResourceManager.GetString("Settings_SwitchAdjacentDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Left: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_SwitchAdjacentDesktop_SwitchLeft {
            get {
                return ResourceManager.GetString("Settings_SwitchAdjacentDesktop_SwitchLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Right: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_SwitchAdjacentDesktop_SwitchRight {
            get {
                return ResourceManager.GetString("Settings_SwitchAdjacentDesktop_SwitchRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Switch to specified desktop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_SwitchSpecifiedDesktop {
            get {
                return ResourceManager.GetString("Settings_SwitchSpecifiedDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_SwitchSpecifiedDesktop_Add {
            get {
                return ResourceManager.GetString("Settings_SwitchSpecifiedDesktop_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Previous: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_SwitchSpecifiedDesktop_Previous {
            get {
                return ResourceManager.GetString("Settings_SwitchSpecifiedDesktop_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove last に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_SwitchSpecifiedDesktop_RemoveLast {
            get {
                return ResourceManager.GetString("Settings_SwitchSpecifiedDesktop_RemoveLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Resize to fit desktops に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_SwitchSpecifiedDesktop_ResizeToFit {
            get {
                return ResourceManager.GetString("Settings_SwitchSpecifiedDesktop_ResizeToFit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Task View に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_TaskView {
            get {
                return ResourceManager.GetString("Settings_TaskView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show Task View: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_TaskView_ShowTaskView {
            get {
                return ResourceManager.GetString("Settings_TaskView_ShowTaskView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Switch Window: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_TaskView_ShowWindowSwitch {
            get {
                return ResourceManager.GetString("Settings_TaskView_ShowWindowSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toggle desktop notification: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ToggleDesktopNotification {
            get {
                return ResourceManager.GetString("Settings_ToggleDesktopNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show current desktop info in tray に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ToggleTrayIconInfo {
            get {
                return ResourceManager.GetString("Settings_ToggleTrayIconInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tray Icon に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_TrayIcon {
            get {
                return ResourceManager.GetString("Settings_TrayIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unpin window: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Unpin {
            get {
                return ResourceManager.GetString("Settings_Unpin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Version に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Version {
            get {
                return ResourceManager.GetString("Settings_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Application is running in the background. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TaskTray_FirstTimeMessage {
            get {
                return ResourceManager.GetString("TaskTray_FirstTimeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E&amp;xit (X) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TaskTray_Menu_Exit {
            get {
                return ResourceManager.GetString("TaskTray_Menu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Settings (S) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TaskTray_Menu_Settings {
            get {
                return ResourceManager.GetString("TaskTray_Menu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Desktop {0}/{1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TaskTray_TooltipText_DesktopCount {
            get {
                return ResourceManager.GetString("TaskTray_TooltipText_DesktopCount", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Add from applications….
        /// </summary>
        public static string Placement_AddFromApp {
            get {
                return ResourceManager.GetString("Placement_AddFromApp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add entry.
        /// </summary>
        public static string Placement_AddManual {
            get {
                return ResourceManager.GetString("Placement_AddManual", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string Placement_AppColumn {
            get {
                return ResourceManager.GetString("Placement_AppColumn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Browse for an executable….
        /// </summary>
        public static string Placement_Browse {
            get {
                return ResourceManager.GetString("Placement_Browse", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to _Cancel.
        /// </summary>
        public static string Placement_Cancel {
            get {
                return ResourceManager.GetString("Placement_Cancel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Placement_Choose {
            get {
                return ResourceManager.GetString("Placement_Choose", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Choose an application.
        /// </summary>
        public static string Placement_ChooseApp {
            get {
                return ResourceManager.GetString("Placement_ChooseApp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Settings changed elsewhere. The unsaved editor was closed; review the current rules before editing again..
        /// </summary>
        public static string Placement_ConfigurationChanged {
            get {
                return ResourceManager.GetString("Placement_ConfigurationChanged", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete rule.
        /// </summary>
        public static string Placement_Delete {
            get {
                return ResourceManager.GetString("Placement_Delete", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An enabled rule already exists for this application. Cancel and edit that rule, or disable one of the rules..
        /// </summary>
        public static string Placement_Duplicate {
            get {
                return ResourceManager.GetString("Placement_Duplicate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Automatically place new app windows.
        /// </summary>
        public static string Placement_Enable {
            get {
                return ResourceManager.GetString("Placement_Enable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string Placement_EnabledColumn {
            get {
                return ResourceManager.GetString("Placement_EnabledColumn", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Enter an executable path or choose an application..
        /// </summary>
        public static string Placement_EnterPath {
            get {
                return ResourceManager.GetString("Placement_EnterPath", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Executable files (*.exe).
        /// </summary>
        public static string Placement_ExeFilter {
            get {
                return ResourceManager.GetString("Placement_ExeFilter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The application identity could not be verified. Choose another entry point..
        /// </summary>
        public static string Placement_IdentityUnavailable {
            get {
                return ResourceManager.GetString("Placement_IdentityUnavailable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Installed applications.
        /// </summary>
        public static string Placement_Installed {
            get {
                return ResourceManager.GetString("Placement_Installed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter a desktop name. Spaces are matched exactly..
        /// </summary>
        public static string Placement_InvalidName {
            get {
                return ResourceManager.GetString("Placement_InvalidName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter a whole number of 1 or greater..
        /// </summary>
        public static string Placement_InvalidNumber {
            get {
                return ResourceManager.GetString("Placement_InvalidNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The executable could not be read. Check the path..
        /// </summary>
        public static string Placement_InvalidPath {
            get {
                return ResourceManager.GetString("Placement_InvalidPath", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This entry does not identify a verifiable executable. Choose its actual executable or open window..
        /// </summary>
        public static string Placement_LauncherOnly {
            get {
                return ResourceManager.GetString("Placement_LauncherOnly", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Check this executable path: a shortcut may point to a launcher rather than the application window..
        /// </summary>
        public static string Placement_LauncherWarning {
            get {
                return ResourceManager.GetString("Placement_LauncherWarning", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Loading applications… You can cancel editing..
        /// </summary>
        public static string Placement_Loading {
            get {
                return ResourceManager.GetString("Placement_Loading", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Desktop name.
        /// </summary>
        public static string Placement_NameColumn {
            get {
                return ResourceManager.GetString("Placement_NameColumn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Place by desktop name.
        /// </summary>
        public static string Placement_NameList {
            get {
                return ResourceManager.GetString("Placement_NameList", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No applications found..
        /// </summary>
        public static string Placement_NoCandidates {
            get {
                return ResourceManager.GetString("Placement_NoCandidates", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Desktop number.
        /// </summary>
        public static string Placement_NumberColumn {
            get {
                return ResourceManager.GetString("Placement_NumberColumn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Place by desktop number.
        /// </summary>
        public static string Placement_NumberList {
            get {
                return ResourceManager.GetString("Placement_NumberList", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Executable path.
        /// </summary>
        public static string Placement_PathColumn {
            get {
                return ResourceManager.GetString("Placement_PathColumn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The executable path could not be confirmed..
        /// </summary>
        public static string Placement_PathUnavailable {
            get {
                return ResourceManager.GetString("Placement_PathUnavailable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Applications could not be loaded. Try refreshing, an open window, or an executable file..
        /// </summary>
        public static string Placement_QueryFailed {
            get {
                return ResourceManager.GetString("Placement_QueryFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Restart monitoring.
        /// </summary>
        public static string Placement_Restart {
            get {
                return ResourceManager.GetString("Placement_Restart", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save again.
        /// </summary>
        public static string Placement_RetrySave {
            get {
                return ResourceManager.GetString("Placement_RetrySave", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enable this rule.
        /// </summary>
        public static string Placement_RuleEnabled {
            get {
                return ResourceManager.GetString("Placement_RuleEnabled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The change is active in memory, but could not be saved to disk. Check the settings storage and save again before closing..
        /// </summary>
        public static string Placement_SaveFailed {
            get {
                return ResourceManager.GetString("Placement_SaveFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Placement_Search {
            get {
                return ResourceManager.GetString("Placement_Search", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to App placement.
        /// </summary>
        public static string Placement_Title {
            get {
                return ResourceManager.GetString("Placement_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Application (name unavailable).
        /// </summary>
        public static string Placement_UnknownApplication {
            get {
                return ResourceManager.GetString("Placement_UnknownApplication", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Running applications.
        /// </summary>
        public static string Placement_Windows {
            get {
                return ResourceManager.GetString("Placement_Windows", resourceCulture);
            }
        }
        public static string Placement_OpenApply {
            get {
                return ResourceManager.GetString("Placement_OpenApply", resourceCulture);
            }
        }
        public static string Placement_ApplyNotSelected {
            get {
                return ResourceManager.GetString("Placement_ApplyNotSelected", resourceCulture);
            }
        }
        public static string Placement_ApplyTitle {
            get {
                return ResourceManager.GetString("Placement_ApplyTitle", resourceCulture);
            }
        }
        public static string Placement_ApplyIntro {
            get {
                return ResourceManager.GetString("Placement_ApplyIntro", resourceCulture);
            }
        }
        public static string Placement_WindowColumn {
            get {
                return ResourceManager.GetString("Placement_WindowColumn", resourceCulture);
            }
        }
        public static string Placement_SourceColumn {
            get {
                return ResourceManager.GetString("Placement_SourceColumn", resourceCulture);
            }
        }
        public static string Placement_TargetColumn {
            get {
                return ResourceManager.GetString("Placement_TargetColumn", resourceCulture);
            }
        }
        public static string Placement_ResultColumn {
            get {
                return ResourceManager.GetString("Placement_ResultColumn", resourceCulture);
            }
        }
        public static string Placement_RefreshWindows {
            get {
                return ResourceManager.GetString("Placement_RefreshWindows", resourceCulture);
            }
        }
        public static string Placement_StopApply {
            get {
                return ResourceManager.GetString("Placement_StopApply", resourceCulture);
            }
        }
        public static string Placement_CloseApply {
            get {
                return ResourceManager.GetString("Placement_CloseApply", resourceCulture);
            }
        }
        public static string Placement_ApplySelection {
            get {
                return ResourceManager.GetString("Placement_ApplySelection", resourceCulture);
            }
        }
        public static string Placement_DesktopNumber {
            get {
                return ResourceManager.GetString("Placement_DesktopNumber", resourceCulture);
            }
        }
        public static string Placement_DesktopUnknown {
            get {
                return ResourceManager.GetString("Placement_DesktopUnknown", resourceCulture);
            }
        }
        public static string Placement_ReadyToApply {
            get {
                return ResourceManager.GetString("Placement_ReadyToApply", resourceCulture);
            }
        }
        public static string Placement_Applying {
            get {
                return ResourceManager.GetString("Placement_Applying", resourceCulture);
            }
        }
        public static string Placement_ApplyDisabled {
            get {
                return ResourceManager.GetString("Placement_ApplyDisabled", resourceCulture);
            }
        }
        public static string Placement_ApplyNoRules {
            get {
                return ResourceManager.GetString("Placement_ApplyNoRules", resourceCulture);
            }
        }
        public static string Placement_ApplyPreparing {
            get {
                return ResourceManager.GetString("Placement_ApplyPreparing", resourceCulture);
            }
        }
        public static string Placement_ApplyPaused {
            get {
                return ResourceManager.GetString("Placement_ApplyPaused", resourceCulture);
            }
        }
        public static string Placement_ApplyStopping {
            get {
                return ResourceManager.GetString("Placement_ApplyStopping", resourceCulture);
            }
        }
        public static string Placement_ApplySuspended {
            get {
                return ResourceManager.GetString("Placement_ApplySuspended", resourceCulture);
            }
        }
        public static string Placement_ApplyChanged {
            get {
                return ResourceManager.GetString("Placement_ApplyChanged", resourceCulture);
            }
        }
        public static string Placement_ApplyEmpty {
            get {
                return ResourceManager.GetString("Placement_ApplyEmpty", resourceCulture);
            }
        }
        public static string Placement_ApplyReview {
            get {
                return ResourceManager.GetString("Placement_ApplyReview", resourceCulture);
            }
        }
        public static string Placement_ApplyCancelled {
            get {
                return ResourceManager.GetString("Placement_ApplyCancelled", resourceCulture);
            }
        }
        public static string Placement_ApplyQueryFailed {
            get {
                return ResourceManager.GetString("Placement_ApplyQueryFailed", resourceCulture);
            }
        }
        public static string Placement_ApplyRunning {
            get {
                return ResourceManager.GetString("Placement_ApplyRunning", resourceCulture);
            }
        }
        public static string Placement_ApplyFinished {
            get {
                return ResourceManager.GetString("Placement_ApplyFinished", resourceCulture);
            }
        }
        public static string Placement_ApplyFailed {
            get {
                return ResourceManager.GetString("Placement_ApplyFailed", resourceCulture);
            }
        }
        public static string Placement_OutcomeMoved {
            get {
                return ResourceManager.GetString("Placement_OutcomeMoved", resourceCulture);
            }
        }
        public static string Placement_OutcomeAlreadyPlaced {
            get {
                return ResourceManager.GetString("Placement_OutcomeAlreadyPlaced", resourceCulture);
            }
        }
        public static string Placement_OutcomeNoRule {
            get {
                return ResourceManager.GetString("Placement_OutcomeNoRule", resourceCulture);
            }
        }
        public static string Placement_OutcomeExcluded {
            get {
                return ResourceManager.GetString("Placement_OutcomeExcluded", resourceCulture);
            }
        }
        public static string Placement_OutcomeChanged {
            get {
                return ResourceManager.GetString("Placement_OutcomeChanged", resourceCulture);
            }
        }
        public static string Placement_OutcomeCancelled {
            get {
                return ResourceManager.GetString("Placement_OutcomeCancelled", resourceCulture);
            }
        }
        public static string Placement_OutcomeTimedOut {
            get {
                return ResourceManager.GetString("Placement_OutcomeTimedOut", resourceCulture);
            }
        }
        public static string Placement_OutcomeUnavailable {
            get {
                return ResourceManager.GetString("Placement_OutcomeUnavailable", resourceCulture);
            }
        }
        public static string Placement_OutcomeDestinationUnavailable {
            get {
                return ResourceManager.GetString("Placement_OutcomeDestinationUnavailable", resourceCulture);
            }
        }
        public static string Placement_OutcomeMoveFailed {
            get {
                return ResourceManager.GetString("Placement_OutcomeMoveFailed", resourceCulture);
            }
        }
        public static string Placement_OutcomeUnconfirmed {
            get {
                return ResourceManager.GetString("Placement_OutcomeUnconfirmed", resourceCulture);
            }
        }
        public static string Placement_OutcomeMonitorPaused {
            get {
                return ResourceManager.GetString("Placement_OutcomeMonitorPaused", resourceCulture);
            }
        }
    }
}
